### ISSUE TITLE
Training data information (indices)

### ISSUE THREAD

**Issue by dedmari** [hpkim0512/Deep_MRI_Unet#1]
Could you please specify the patient index per MR, so that it will be easy to identify slices with respect to particular patient.

**Comment by hpkim0512** [comment]
We used 38 and 18 patients MR image for training and test respectively.
The patient indes (end) for training are, 
22, 44, 66, 88, 110, 132, 159, 186, 214, 241, 269, 296, 318, 340, 368, 395, 422, 449, 471, 493, 515, 537, 564, 591, 613, 635, 657, 679, 701, 723, 745, 767, 789, 811, 838, 865, 887, 911, 933, 955, 977, 999, 1021, 1043, 1071, 1099, 1127, 1155, 1183, 1211, 1233, 1255, 1282, 1309, 1336, 1363, 1385, 1407.

The patient indes (end) for test are, 
19, 42, 66, 94, 116, 142, 162, 189, 211, 233, 255, 277, 304, 331, 359, 387, 409, 431.

**Comment by dedmari** [comment]
Thanks a lot for the information.
