### ISSUE TITLE
No pre-trained model

### ISSUE THREAD

**Issue by dedmari** [hpkim0512/Deep_MRI_Unet#2]
Is there any pre-trained model available?

**Comment by hpkim0512** [comment]
Thank you for your attention.
I uploaded the pre-trained model on README.
Please check about that.
Thank you

**Comment by vegarant** [comment]
Do you have the sampling pattern you used for the pretrained network?

**Comment by hpkim0512** [comment]
We used a uniform subsampling of factor 4 (25% k-space data - 64 lines of a total 256 lines) with a few low frequencies (abot 4% k-space data - 12 lines of a total 256 lines). For further details, please see [https://arxiv.org/pdf/1709.02576.pdf](https://arxiv.org/pdf/1709.02576.pdf)

**Comment by vegarant** [comment]
I was unsure if you started the sampling the at line 0,1,2 or 3,  since I open the data in Matlab, and did a `fft2` on it. The result was quite surprisingly non-sparse. However, using `numpy.fft.fft2` gives a sparse result, so I can see that you started on line 0.

Thanks for the quit reply.
